/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chikong_ndkdemo_FFmpegRun */

#ifndef _Included_com_chikong_ndkdemo_FFmpegRun
#define _Included_com_chikong_ndkdemo_FFmpegRun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chikong_ndkdemo_FFmpegRun
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_chikong_ndkdemo_FFmpegRun_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
